### ISSUE TITLE
Evaluator needs to take in multiple expressions

### ISSUE THREAD

**Issue by zana-a** [zana-a/milkshake#5]
Evaluator needs to take in multiple expressions so that when the transpiler can call the evaluator once on each valid value of a property.

For example:

```css
.example {
    margin: 10% 100cm 32px (12 + 2)px
}
```
